In [56]:
import pandas as pd
import glob
import numpy as np
import os

In [83]:
#df = pd.read_csv(filename, header = 0, index_col = None)
#where the data files are located
folder = "DD08_Short2"
all_files = glob.glob(folder + "/*.csv")
newfolder = "interspike_int"
subject = folder.split("_")[0]

# analyze each file in the folder
for filename in all_files:
    print(filename + " started")
    file = filename.split('.')[0]
    df = pd.read_csv(filename, index_col=False, header=None, names = ["C1","C2"])
    df2 = pd.DataFrame(columns = ["ISI1","ISI2"])
    #make new DataFrame with columns
    df2["ISI1"] = df.C1.diff()
    if df.C2.notnull().any():
        df2["ISI2"] = df.C2.diff()
    else:
        print("skip col 2")
    df2.to_csv(newfolder + "/" + file + "_ISI.csv")
print("All Done")

DD08_Short2/1_31.csv started
skip col 2
DD08_Short2/3_27.csv started
DD08_Short2/3_26.csv started
DD08_Short2/4_11.csv started
DD08_Short2/3_25.csv started
DD08_Short2/3_28.csv started
DD08_Short2/4_09.csv started
DD08_Short2/3_14.csv started
DD08_Short2/3_15.csv started
DD08_Short2/3_12.csv started
DD08_Short2/1_29.csv started
skip col 2
DD08_Short2/2_22.csv started
DD08_Short2/2_21.csv started
DD08_Short2/2_19.csv started
All Done

In [84]:
# create single file with all frequencies
path = newfolder + "/" + folder 
freq_files = glob.glob(path + "/*.csv")

li = []

for filename in freq_files:
    fdf = pd.read_csv(filename, index_col=0, header=0)
    li.append(fdf)

frame = pd.concat(li, axis=0, ignore_index=True,sort = True)
big_path = subject
frame.to_csv(subject + "_forhist_ISI.csv")

In [85]:
frame

           ISI1     ISI2
0           NaN      NaN
1        0.0278   2.5360
2        0.0888   1.1512
3        0.6380   0.0770
4        0.3346   0.7448
5        0.7128   0.0386
6        1.0638   0.2292
7        0.3308   0.1526
8        0.0878   0.2920
9        0.0926   0.2176
10       0.0434   0.1008
11       0.0356   0.6776
12       0.1970   0.0662
13       0.0952   1.8100
14       0.1416   0.0368
15       0.0730   0.7656
16       0.4128   0.1420
17       0.0652   0.0270
18       0.0726   0.0374
19       0.1152   0.0426
20       0.0298   0.1220
21       0.0764   1.1832
22       0.4192   0.0850
23       0.0754   0.5900
24       0.0324   0.1122
25       0.1040   0.0154
26       0.0370   0.0236
27       0.0328   0.0142
28       0.0348   0.0360
29       0.0816   0.1090
...         ...      ...
1909203     NaN   0.1618
1909204     NaN   0.0940
1909205     NaN   0.1930
1909206     NaN   0.1358
1909207     NaN   0.0996
1909208     NaN   0.2532
1909209     NaN   0.1206
1909210     NaN   0.1092
1909211     NaN   0.1798
1909212     NaN   0.2066
1909213     NaN   0.0914
1909214     NaN   0.5140
1909215     NaN   0.1736
1909216     NaN   0.1456
1909217     NaN   0.2942
1909218     NaN   0.1356
1909219     NaN   0.2010
1909220     NaN   0.0978
1909221     NaN   0.4830
1909222     NaN   0.1628
1909223     NaN   0.1432
1909224     NaN   0.2124
1909225     NaN   0.2546
1909226     NaN   0.2296
1909227     NaN  15.9870
1909228     NaN   0.6112
1909229     NaN   0.4294
1909230     NaN   0.7148
1909231     NaN   0.3428
1909232     NaN   6.2210

[1909233 rows x 2 columns]